import { Router } from "express";
import { appealRoutes } from "@/routes/appealRoutes.js";
import { attachmentRoutes } from "@/routes/attachmentRoutes.js";
import { auditRoutes } from "@/routes/auditRoutes.js";
import { authRoutes } from "@/routes/authRoutes.js";
import { customerAppealRoutes } from "@/routes/customerAppealRoutes.js";
import { customerNotificationRoutes } from "@/routes/customerNotificationRoutes.js";
import { epicRoutes } from "@/routes/epicRoutes.js";
import { leadRoutes } from "@/routes/leadRoutes.js";
import { notificationRoutes } from "@/routes/notificationRoutes.js";
import { pushRoutes } from "@/routes/pushRoutes.js";
import { reportRoutes } from "@/routes/reportRoutes.js";
import { userRoutes } from "@/routes/userRoutes.js";
import { vacationRoutes } from "@/routes/vacationRoutes.js";
import { absenceRoutes } from "@/routes/absenceRoutes.js";
import { businessTripRoutes } from "@/routes/businessTripRoutes.js";

export const apiV1Router = Router();

apiV1Router.use("/auth", authRoutes);
apiV1Router.use("/users", userRoutes);
apiV1Router.use("/appeals", appealRoutes);
apiV1Router.use("/customer/appeals", customerAppealRoutes);
apiV1Router.use("/attachments", attachmentRoutes);
apiV1Router.use("/epics", epicRoutes);
apiV1Router.use("/reports", reportRoutes);
apiV1Router.use("/notifications", notificationRoutes);
apiV1Router.use("/customer/notifications", customerNotificationRoutes);
apiV1Router.use("/push", pushRoutes);
apiV1Router.use("/audit", auditRoutes);
apiV1Router.use("/leads", leadRoutes);
apiV1Router.use("/vacation-requests", vacationRoutes);
apiV1Router.use("/absence-requests", absenceRoutes);
apiV1Router.use("/business-trip-requests", businessTripRoutes);
